<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class EmployeeFinalScore extends Model
{
    use HasFactory;
    protected $table = 'tb_employee_final_score';
    protected $primaryKey = 'id';
    protected $fillable = ["id",
                            "import_id",
                            "import_score_id",
                            "rec_year",
                            "employee_no",
                            "status_assessed",
                            "service_days",
                            "attendance_sl",
                            "attendance_pl",
                            "attendance_late",
                            "attendance_abs",
                            "attendance_abt",
                            "attendance_cl",
                            "attendance_ol",
                            "attendance_sus",
                            "attendance_wwar",
                            "attendance_vwar",
                            "previous_form",
                            "form_import",
                            "group_form_id",
                            "previous_evaluator_no",
                            "evaluator_no",
                            "evaluator_active",
                            "evaluator_name_th",
                            "evaluator_name_en",
                            "evaluation_criteria_score1",
                            "evaluation_criteria_score2",
                            "evaluation_criteria_score3",
                            "evaluation_criteria_score4",
                            "evaluation_criteria_score5",
                            "evaluation_criteria_score6",
                            "evaluation_criteria_score7",
                            "evaluation_criteria_score8",
                            "evaluation_criteria_score10",
                            "evaluation_criteria_score_old1",
                            "evaluation_criteria_score_old2",
                            "evaluation_criteria_score_old3",
                            "evaluation_criteria_score_old4",
                            "evaluation_criteria_score_old5",
                            "evaluation_criteria_score_old6",
                            "evaluation_criteria_score_old7",
                            "evaluation_criteria_score_old8",
                            "evaluation_criteria_score_old10",
                            "compliance_score",
                            "attendance_score",
                            "total_score",
                            "total_score_old",
                            "pa_grade",
                            "adjust_grade_old1",
                            "adjust_grade_old2",
                            "adjust_grade_old3",
                            "adjust_grade",
                            "remark",
                            "status_evaluation",
                            "salary_type",
                            "salary_old",
                            "l800avg_wage",
                            "bsalary_wage",
                            "salary_month_old",
                            "company_suggested_per",
                            "company_suggestged_amount",
                            "company_suggestged_new_basic",
                            "grade_proposed_old",
                            "grade_proposed",
                            "percent_proposed_old",
                            "percent_proposed",
                            "amount_proposed",
                            "salary_new",
                            "salary_month_new",
                            "final_by_md_gm_amount",
                            "approve_date",
                            "status_pa",
                            "status_salary",
                            "remark_grade",
                            "comment",
                            "dept_manager_approve_score",
                            "dmgm_approve_salary",
                            "created_by",
                            "updated_by",
                            "created_at",
                            "updated_at"];
     public $timestamp = false;
}
